### ISSUE TITLE
Unable to run textual inversion example in AWS Sagemaker

### ISSUE THREAD

**Issue by karleikongsiri** [huggingface/diffusers#2309]
**Description**
I am trying to run the textual inversion example in AWS Sagemaker, but I keep getting the following error:

TypeError: SageMakerConfig.__init__() missing 1 required positional argument: 'image_uri'

I have followed all of the instructions listed in the readME and this is what my accelerate_cofig.yaml looks like:

base_job_name: accelerate-sagemaker-1
compute_environment: AMAZON_SAGEMAKER
distributed_type: DATA_PARALLEL
dynamo_backend: 'NO'
ec2_instance_type: ml.p3.16xlarge
gpu_ids: all
iam_role_name: arn:aws:iam::748951283826:role/SageMakerExecutionRole
mixed_precision: fp16
num_machines: 1
profile: default
py_version: py38
pytorch_version: 1.10.2
region: us-east-1
transformers_version: 4.17.0
use_cpu: false

Additionally, I tried adding a custom docker image, so that image_uri was in the config as well. For both of these configs I get the same error. Would appreciate some help. Thanks

**Comment by jndietz** [comment]
I think you're missing `image_uri` in your YAML.

https://huggingface.co/docs/accelerate/usage_guides/sagemaker#advanced-features

```yaml
base_job_name: accelerate-sagemaker-1
compute_environment: AMAZON_SAGEMAKER
distributed_type: DATA_PARALLEL
ec2_instance_type: ml.p3.16xlarge
iam_role_name: xxxxx
image_uri: null
mixed_precision: fp16
num_machines: 1
profile: xxxxx
py_version: py38
pytorch_version: 1.10.2
region: us-east-1
transformers_version: 4.17.0
use_cpu: false
```
