### ISSUE TITLE
TensorRT Example TypeError

### ISSUE THREAD

**Issue by djj0s3** [huggingface/diffusers#3181]
### Describe the bug
Running the example in the repo for TensorRT receiving this error:
```
 File "/root/.cache/huggingface/modules/diffusers_modules/git/stable_diffusion_tensorrt_txt2img.py", line 706, in to
    super().to(torch_device, silence_dtype_warnings)
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 643, in to
    module.to(torch_device, torch_dtype)
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1126, in to
    device, dtype, non_blocking, convert_to_format = torch._C._nn._parse_to(*args, **kwargs)
TypeError: to() received an invalid combination of arguments - got (str, bool), but expected one of:
 * (torch.device device, torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (Tensor tensor, bool non_blocking, bool copy, *, torch.memory_format memory_format)
```

### Reproduction

Run the example in the repo for TensorRT: https://github.com/huggingface/diffusers/blob/main/examples/community/README.md#tensorrt-text2image-stable-diffusion-pipeline

### System Info

  cuda: "11.7"
  python_version: "3.9.16"
  system_packages:
    - "python3-pip"
  python_packages:
    - "diffusers==0.15.1"
    - "torch==2.0.0"
    - "ftfy==6.1.1"
    - "scipy==1.9.3"
    - "transformers==4.25.1"
    - "accelerate==0.15.0"
    - "huggingface-hub==0.13.2"
    - "nvidia-pyindex==1.0.9"
    - "tensorrt==8.6.0"

**Comment by init-22** [comment]
@djj0s3   Because in the at line number 657 in pipeline_utils.py torch_dtype is False, so I've added

if not torch_dtype: torch_dtype = torch.float16 

before module.to(torch_device, torch_dtype)

but now I am getting the following error,
Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported. 

Anybody have any hint on this? seems like it has to do with the TRT and ONNX versions 

@djj0s3  can you still try the changes and see if it works, I changed my TRT, ONNX version, might have got them messed up

**Comment by init-22** [comment]
Also, in the same  (to) function  
`    def to(
        self,
        torch_device: Optional[Union[str, torch.device]] = None,
        torch_dtype: Optional[torch.dtype] = None,
        silence_dtype_warnings: bool = False,
    ):`

which means torch_dtype should be None if it is not passed but I found that is it is False at line number 657 while debugging, anybody have any idea? I actually wanted to change 
`torch_dtype: Optional[torch.dtype] = None,`

to 

`torch_dtype: Optional[torch.dtype] = torch.float16`

**Comment by djj0s3** [comment]
No luck, but I sense you're right on the version numbers of the packages. Interestingly looking at [examples/community/stable_unclip.py](https://github.com/huggingface/diffusers/blob/1d7b4b60b7b7e19a0347da5a04ec76c045d8dbf0/examples/community/stable_unclip.py) the call doesn't include the boolean:
https://github.com/huggingface/diffusers/blob/7e6886f5e93ca9bb1e6d4beece46fe1e43b819c2/examples/community/stable_diffusion_tensorrt_txt2img.py#L705

```
def to(self, torch_device: Optional[Union[str, torch.device]] = None, silence_dtype_warnings: bool = False):
super().to(torch_device, silence_dtype_warnings)
```

**Comment by init-22** [comment]
Yeah interesting!

**Comment by djj0s3** [comment]
Update and some progress! This example needs a big ol disclaimer. Getting it all running even on a lambdalabs instance was super not fun.

pre-reqs:
You need the latest stable NVIDIA drivers for your GPU. If you're using a cloud instance, your cloud GPU may not be running it. So get that all squared away first.  Then some other dependencies:
```
  cuda: "11.7"
  python_version: "3.9.16"
  system_packages:
    - "python3-pip"
  python_packages:
    - "pip==23.1"
    - "torchvision==0.14.1"
    - "torchaudio==0.13.1"
    - "diffusers==0.15.1"
    - "ftfy==6.1.1"
    - "scipy==1.10.1"
    - "transformers==4.28.1"
    - "accelerate==0.17.1"
    - "huggingface-hub==0.13.4"
    - "tensorrt==8.6.0"
    - "torch==1.13.1" 
    - "nvidia-pyindex==1.0.9"
    - pip install colored polygraphy --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com
    - pip install onnx --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com
    - pip install onnx_graphsurgeon --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com
    - pip install onnxruntime --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com
```
