### ISSUE TITLE
TorchDynamo with Pipeline loading

### ISSUE THREAD

**Issue by thepowerfuldeez** [huggingface/diffusers#3403]
### Describe the bug

Hi! I am using accelerate + diffusers for fine-tuning of stable diffusion using this script:
https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py 
I have pytorch 2.0 and accelerate recently supports torch dynamo for improving speed of training.
However, when I set `dynamo_backend = "inductor"` in Accelerator class, I am getting error
in validation stage:

line 67: https://github.com/huggingface/diffusers/blob/1a5797c6d4491a879ea5285c4efc377664e0332d/examples/text_to_image/train_text_to_image.py#L67-L76
` of type: <class 'torch._dynamo.eval_frame.OptimizedModule'>, but should be <class 'diffusers.models.modeling_utils.ModelMixin'>`

The issue is for unet

### Reproduction

https://github.com/huggingface/diffusers/blob/1a5797c6d4491a879ea5285c4efc377664e0332d/examples/text_to_image/train_text_to_image.py#L67 

### System Info

pytorch==2.0.1
diffusers==0.17.0.dev0
accelerate==0.19.0

**Comment by thepowerfuldeez** [comment]
related https://github.com/huggingface/diffusers/issues/2709

**Comment by patrickvonplaten** [comment]
Hey @thepowerfuldeez, 

Thanks for the issue! Could you add a reproducible code snippet (the command you use to start training + the accelerate config?) 

This would be of great help :-) 

Also cc @sayakpaul

**Comment by thepowerfuldeez** [comment]
@patrickvonplaten 
Sure! I start training with aforementioned script file as
`accelerate launch train_text_to_image.py` specifying `mixed_precision=bf16` and `dynamo_backend=inductor` only.
It’s auto detected 8 gpus so I’m using `num_processes=8`
First iteration it hangs for a while as it’s compiling the code with dynamo, and after 2000 steps i perform validation as in the script where the exception is evoked.

I’m afraid I can’t share data to reproduce. However, I could try to prepare gist with commands on sample data to try if you would not be able to reproduce bug.

**Comment by patrickvonplaten** [comment]
Now when I use `torch_dynamo` I'm getting an error message. It's the same script as above, but with `accelerate` changed as follows:
```
compute_environment: LOCAL_MACHINE                                                                                                                                                                                                            
distributed_type: MULTI_GPU                                                                                                                                                                                                                   
downcast_bf16: 'no'                                                                                                    
dynamo_config:                                                                                                                                                                                                                                
  dynamo_backend: INDUCTOR                                                                                             
  dynamo_mode: default                                                                                                 
  dynamo_use_dynamic: false                                
  dynamo_use_fullgraph: false                                                                                          
gpu_ids: all                                                                                                           
machine_rank: 0                                                                                                        
main_training_function: main                                                                                           
mixed_precision: fp16                                                                                                                                                                                                                         
num_machines: 1                                                                                                                                                                                                                               
num_processes: 2                                                                                                       
rdzv_backend: static                                                                                                                                                                                                                          
same_network: true                                                                                                                                                                                                                            
tpu_env: []                                                                                                                                                                                                                                   
tpu_use_cluster: false                                                                                                                                                                                                                        
tpu_use_sudo: false                                                                                                                                                                                                                           
use_cpu: false 
```

The error I'm getting is:
```
│ /home/patrick/hf/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py:754 in          │                                                                                                                                          
│ wrap_fx_proxy                                                                                    │                                                                                                                                          
│                                                                                                  │                                                                                                                                          
│   751                                                                                            │                                                                                                                                          
│   752                                                                                            │                                                                                                                                          
│   753 def wrap_fx_proxy(tx, proxy, example_value=None, **options):                               │                                                                                                                                          
│ ❱ 754 │   return wrap_fx_proxy_cls(                                                              │                                                                                                                                          
│   755 │   │   target_cls=TensorVariable,                                                         │                                                                                                                                          
│   756 │   │   tx=tx,                                                                             │                                                                                                                                          
│   757 │   │   proxy=proxy,                                                                       │                                                                                                                                          
│                                                                                                  │                                                                                                                                          
│ /home/patrick/hf/lib/python3.10/site-packages/torch/_dynamo/variables/builder.py:812 in          │                                                                                                                                          
│ wrap_fx_proxy_cls                                                                                │                                                                                                                                          
│                                                                                                  │                                                                                                                                          
│   809 │   │   │   │   "ignore_subclass": ignore_subclass,                                        │                                                                                                                                          
│   810 │   │   │   │   "is_tensor": target_cls is TensorVariable,                                 │                                                                                                                                          
│   811 │   │   │   }                                                                              │                                                                                                                                          
│ ❱ 812 │   │   │   assert "source" in options and options["source"] is not None                   │                                                                                                                                          
│   813 │   │   │   kwargs["source"] = options["source"]                                           │                                                                                                                                          
│   814 │   │   │   example_value = wrap_to_fake_tensor_and_record(                                │                                                                                                                                          
│   815 │   │   │   │   example_value, tx=tx, **kwargs                                             │                                                                                                                                          
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                                                                                          
AssertionError:                                                                                                                                                                                                                               
                                                                                                                                                                                                                                              
from user code:                                                                                                                                                                                                                               
   File "/home/patrick/hf/lib/python3.10/site-packages/torch/random.py", line 23, in get_rng_state                                                                                                                                            
    return default_generator.get_state()                                                                                                                                                                                                      
                                          
[...]
ChildFailedError:                                                                                                                                                                                                                             
============================================================                                                                                                                                                                                  
train_text_to_image.py FAILED                                                                                                                                                                                                                 
------------------------------------------------------------                                                                                                                                                                                  
Failures:                                                                                                                                                                                                                                     
  <NO_OTHER_FAILURES>                                                                                                                                                                                                                         
------------------------------------------------------------                                                                                                                                                                                  
Root Cause (first observed failure):                                                                                                                                                                                                          
[0]:                                                                                                                                                                                                                                          
  time      : 2023-05-16_10:54:51                                                                                                                                                                                                             
  host      : audace                                                                                                                                                                                                                          
  rank      : 1 (local_rank: 1)                                                                                                                                                                                                               
  exitcode  : 1 (pid: 3183779)                                                                                                                                                                                                                
  error_file: <N/A>                                                                                                                                                                                                                           
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html    
```
