### ISSUE TITLE
No any GPU memory saved when using zero3 to train train_text_to_image.py

### ISSUE THREAD

**Issue by wangmiaowei** [huggingface/diffusers#3774]
### Describe the bug

In order to save GPU memory, I adopt the zero3 FSDP strategy in deepspeed. And then full finetune train train_text_to_image.py. However, I do not see any memory savings. Is there any problem here?

### Reproduction

My default_config.yaml
```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'fp16'
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
use_cpu: false
```

My runing script:
```
export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export dataset_name="imgs"

accelerate launch --mixed_precision="fp16" --multi_gpu  train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$dataset_name \
  --use_ema \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --max_train_steps=100 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --checkpointing_steps=1000 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir sd_qunhe_output

```

### System Info

- `diffusers` version: 0.18.0.dev0
- Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.27
- Python version: 3.9.16
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.29.2
- Accelerate version: 0.19.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
