### ISSUE TITLE
Multi-GPU Training Runs Slower Than Single-GPU Training for  SD1.5 text-to-image finetuning

### ISSUE THREAD

**Issue by garg-aayush** [huggingface/diffusers#5197]
### Describe the bug

I am attempting to train SD1.5 ([model](runwayml/stable-diffusion-v1-5)) for text-to-image generation using the [train_text_to_image.py](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py) script on a custom dataset. Given the large size of the dataset, and having access to a server with 2 A100 GPUs, I initiated multi-GPU training as instructed in the [README](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/README.md) file.

Unexpectedly, the multi-GPU training operates significantly slower and does not deliver the anticipated speed-up. For instance, I conducted a test where a single GPU training was run with `batch_size=1` for `15000 steps`, and a two-GPU training was run with `batch_size=2` for `7500 steps` - thus equating the total number of examples seen during training in both scenarios. I anticipated that the two-GPU training would be at least `1.5/2X` faster, yet it ran slower than the single-GPU training.

Below is a table summarizing the observed performance:

| Training Mode | GPUs | Effective Batch Size | Steps | Iterations/second | Total Run Time |
|:--------------:|:----:|:--------------------:|:-----:|:-----------------:|:--------------:|
| Single GPU     | 1    | 1                    | 15000 | ~2it/s            | 1hr 40m        |
| Two GPU        | 2    | 2                    | 7500  | ~0.84it/s         | 2hr 30m        |

I am seeking assistance to understand what might be going wrong, and how to rectify this issue to achieve the expected performance improvement with multi-GPU training.

### Reproduction

```
# environment info
OS: Linux (Ubuntu 20.04)
CUDA: 11.6
GPUS: 2 A100-PCI (40 GB)
```

```environment info
# create env
conda create -n diffusers python=3.10
pip install torch torchvision
pip install git+https://github.com/huggingface/diffusers
pip install git+https://github.com/huggingface/accelerate
pip install transformers datasets opencv-python jupyter matplotlib
```
See attached [requirements.txt](https://github.com/huggingface/diffusers/files/12736876/requirements.txt) to to see the env packages 

### Single-GPU Training
```
MODEL_NAME="runwayml/stable-diffusion-v1-5"
DATASET_NAME="lambdalabs/pokemon-blip-captions"
STEPS=15000

export CUDA_VISIBLE_DEVICES=0,1
accelerate launch --multi_gpu --num_processes=2 --mixed_precision="fp16" train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$DATASET_NAME \
  --resolution=512 --center_crop --random_flip \
  --dataloader_num_workers=32 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --max_train_steps=$STEPS \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir="sd-pokemon-model" 
```

### Two GPU training
```bash
MODEL_NAME="runwayml/stable-diffusion-v1-5"
DATASET_NAME="lambdalabs/pokemon-blip-captions"
STEPS=7500

export CUDA_VISIBLE_DEVICES=0,1
accelerate launch --multi_gpu --num_processes=2 --mixed_precision="fp16" train_text_to_image.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --dataset_name=$DATASET_NAME \
  --resolution=512 --center_crop --random_flip \
  --dataloader_num_workers=32 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --max_train_steps=$STEPS \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" --lr_warmup_steps=0 \
  --output_dir="sd-pokemon-model" 
```

### Training logs
1. Single GPU Training: 
   - approx `2.1` steps per second (`2.1it/s`)
   - Please see [log_single_gpu.log](https://github.com/huggingface/diffusers/files/12736999/log_single_gpu.log) to see the log for 1 gpu training
   - accelerate config 
```yaml
compute_environment: LOCAL_MACHINE                                                                                                                                                                          
debug: false
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: all 
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

2. Two GPU Training:
   - approx `0.84` steps per second (`1.19s/it`)
   - Please see [log_two_gpu.log](https://github.com/huggingface/diffusers/files/12737087/log_two_gpu.log) to see the log for 1 gpu training
   - accelerate config
```yaml
compute_environment: LOCAL_MACHINE
debug: false  
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all  
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []   
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false 
```
   

### System Info

- `diffusers` version: 0.22.0.dev0
- Platform: Linux-5.4.0-29-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.33.2
- Accelerate version: 0.24.0.dev0
- xFormers version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

### Who can help?

@sayakpaul @yiyixuxu @williamberman @patrickvonplaten
