### ISSUE TITLE
[Refactor] Decouple the different loaders and create a separate `loaders` module

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/diffusers#5669]
Currently, we have a big monolith [`loaders.py`](https://github.com/huggingface/diffusers/blob/main/src/diffusers/loaders.py) that has got all kinds of different loaders classes (`LoraLoaderMixin`, `FromSingleFileMixin`, etc.).

I propose to create a separate `loaders` module now that we have a growing number of different kinds of loader classes. The module will contain (names can be brainstormed):

* lora_loader.py
* single_file_loader.py
* textual_inversion_loader.py
* ...

These are conceptually different things and hence it's better to have them separated like the above. 

Having this level of separation allows us to:

* Promote better readability (we're essentially reducing quite a lot of LoC here) 
* Promote better modularity 
* Promote better separation of concerns 

We should also be able to document the `loaders` module even better with this IMO. 

Curious to hear thoughts from @DN6 and @patrickvonplaten about this.

**Comment by DN6** [comment]
Sounds good to me 👍🏽

**Comment by patrickvonplaten** [comment]
Yes that works for me.

**Comment by sayakpaul** [comment]
@stevhliu now this issue is closed via #5771, would you maybe like to work on dedicated API doc pages for the decoupled loaders and remove the big loaders doc we have? Let me know if you need any clarifications.

**Comment by stevhliu** [comment]
Thanks @sayakpaul! What do you think about the following structure for each loader's dedicated API doc pages?

```yml
- sections:
   - sections:
      - local: api/lora
         title: LoRA
      - local: api/textual_inversion
         title: Textual Inversion
         ...
         ...
         ...
      - local: api/unet
         title: UNet
      title: Loaders
  title: API
```
