### ISSUE TITLE
SDXL "load_lora_weights" results in different ouputs than loading in unet and text encoder in two steps

### ISSUE THREAD

**Issue by To-jak** [huggingface/diffusers#6639]
### Describe the bug

I seem to get very different results depending on how I load the weights of my trained SDXL LoRA.

* In the first experience, I load the weights with the `load_lora_weights` method.

Here is the output for basic text to image pipeline inference:
![first_method_resized_256](https://github.com/huggingface/diffusers/assets/33063955/cd279919-1abc-44a9-97dd-e3d19870585d)

* In the second one, I load the weights with `load_lora_into_unet` and `load_lora_into_text_encoder`.

The output is different (and looks much better imo):
![second_method_resized_256](https://github.com/huggingface/diffusers/assets/33063955/c8279e75-136f-42d0-8fa1-3d5c9e93aff5)

The same generator seed is used for inference.

I got my lora model weights using the [train_dreambooth_lora_sdxl_advanced.py](https://github.com/huggingface/diffusers/blob/v0.25.1/examples/advanced_diffusion_training/train_dreambooth_lora_sdxl_advanced.py) example script and the [dog images](https://huggingface.co/datasets/diffusers/dog-example) from documentation.

The training script performs some operations to convert the state_dict to diffusers, but it does so by using the `diffusers.utils` methods. Anyway, I find it odd to observe this behavior. Thanks! 

### Reproduction

**First experience**, loading the lora weights with the `load_lora_weights` method:

```Python
import torch
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_pretrained(
    'stabilityai/stable-diffusion-xl-base-1.0',
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True
)
pipe.to('cuda')

# Load LoRA with "load_lora_weights"
pipe.load_lora_weights(
    # Path to my trained lora output_dir
    '.cache/training_artifacts/626d7ad2-c5e8-4d58-88a9-42a3114f852d',
    weight_name="pytorch_lora_weights.safetensors",
    adapter_name='test_lora'
)
pipe.set_adapters(["test_lora"], adapter_weights=[1.0])

prompt = 'picture of ohwx character in a bucket'

generator = torch.Generator(device="cuda").manual_seed(42)
pipe(
    prompt=prompt,
    num_inference_steps=20,
    generator=generator
).images[0]
```

**Second experience**, loading the lora weights in two steps, unet then text encoder:

```python
import torch
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_pretrained(
    'stabilityai/stable-diffusion-xl-base-1.0',
    torch_dtype=torch.float16,
    variant="fp16",
    use_safetensors=True
)
pipe.to('cuda')

# Load LoRA with "load_lora_into_unet" and "load_lora_into_text_encoder"
state_dict, network_alphas = StableDiffusionXLPipeline.lora_state_dict(
    # Path to my trained lora output_dir
    '.cache/training_artifacts/626d7ad2-c5e8-4d58-88a9-42a3114f852d',
    weight_name="pytorch_lora_weights.safetensors"
)
pipe.load_lora_into_unet(state_dict, network_alphas, pipe.unet, adapter_name='test_lora')
pipe.load_lora_into_text_encoder(state_dict, network_alphas, pipe.text_encoder, adapter_name='test_lora')
pipe.set_adapters(["test_lora"], adapter_weights=[1.0])

prompt = 'picture of ohwx character in a bucket'

generator = torch.Generator(device="cuda").manual_seed(42)
pipe(
    prompt=prompt,
    num_inference_steps=20,
    generator=generator
).images[0]

```

### System Info

Python: `3.10.12`
diffusers: `0.25.0`
peft: `0.7.1`
accelerate: `0.23.0`
transformers: `4.36.0`
Using GPU in script?: Yes
advanced training script commit hash: https://github.com/huggingface/diffusers/commit/7f551e29ff4ad05615cb38530a8940811f9e5936

### Who can help?

@sayakpaul

**Comment by sayakpaul** [comment]
Cc: @linoytsaban for advanced trainer. 

But in any case we don't have access tp ".cache/training_artifacts/626d7ad2-c5e8-4d58-88a9-42a3114f852d".

**Comment by linoytsaban** [comment]
Hey @To-jak!
Did you use pivotal tuning to train your LoRA? - i.e. enable `--train_text_encoder_ti`?

**Comment by To-jak** [comment]
I made the model weights available here: https://huggingface.co/Tojak/test_lora-dog-626d7ad2-c5e8 🙂

Here are some additional info about the training parameters (did not use `train_text_encoder_ti`):

```yaml
training_parameters:
  adam_beta2: 0.99
  adam_weight_decay: 0.01
  checkpointing_steps: 10000
  instance_prompt: a ohwx character
  learning_rate: 1.0
  max_train_steps: 300
  optimizer: prodigy
  pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
  pretrained_vae_model_name_or_path: madebyollin/sdxl-vae-fp16-fix
  rank: 32
  repeats: 1
  resolution: 1024
  seed: 42
  snr_gamma: 5.0
  text_encoder_lr: 1.0
  train_batch_size: 2
  train_text_encoder: true
  train_text_encoder_frac: 0.8
  train_text_encoder_ti: false
```
